### ISSUE TITLE
Registered Users by Phone Brand: No count for Apple in Bihar

### ISSUE THREAD

**Issue by databeings** [PhonePe/pulse#1]
On Bihar json (link below), Apple doesn't show up at all. Not sure on how to interpret - appears unlikely that PhonePe has no Apple users in Bihar. Q2 FY22 Bihar users data link below:

https://raw.githubusercontent.com/PhonePe/pulse/master/data/aggregated/user/country/india/state/bihar/2021/2.json

**Comment by pradeep-pgop** [comment]
Hi! For that particular quarter, Apple doesn't feature in the top 10 brands, ranked by # of registered users, and is hence covered in the 'Others' category.
