### ISSUE TITLE
Access to district Level Data

### ISSUE THREAD

**Issue by rbkayz** [PhonePe/pulse#2]
Could you also please share APIs to access the district level data i.e. the data that appears on hover? Thanks a lot

**Comment by patilauminfi** [comment]
Yes please !!! Please provide transaction data (types of transactions and amount) at pincode (or atleast) district level.

**Comment by nagarajue-179** [comment]
Hello @rbkayz,

We have added state and district level data under [data > map](https://github.com/PhonePe/pulse/tree/master/data/map) section.

**Comment by nagarajue-179** [comment]
> Hello @rbkayz,
> 
> We have added state and district level data under [data > map](https://github.com/PhonePe/pulse/tree/master/data/map) section.

We have added state / district level data. Pincode level data isn't available for now.

**Comment by rbkayz** [comment]
> > Hello @rbkayz,
> > We have added state and district level data under [data > map](https://github.com/PhonePe/pulse/tree/master/data/map) section.
> 
> We have added state / district level data. Pincode level data isn't available for now.

Thanks a lot boss!
