### ISSUE TITLE
Not sure how this usage data should be interpreted

### ISSUE THREAD

**Issue by Ankur10gen** [PhonePe/pulse#3]
Each year data under /data/aggregated/user/country/india/ has 4 JSON files. I'm not sure if the total devices is sum total across 4 files or should be max/average of these 4.

**Comment by pradeep-pgop** [comment]
Hi @Ankur10gen. Each JSON file represents the data for one calendar year quarter, for example, Jan-Mar, Apr-Jun, etc. The users by device data represents the # of PhonePe users on the particular device brand, at the end of the mentioned quarter. So to get the latest number, that is, for Jun 2021, you'll have to look at the numbers for the Apr-Jun 2021 quarter. Hope this clarifies.

**Comment by Ankur10gen** [comment]
Thanks Pradeep. Makes sense. I have used "max" of these numbers to build the charts on top of this data. https://charts.mongodb.com/charts-phonepepulsedata-qggry/public/dashboards/61404829-298e-4f73-854b-a0dcbce5ffc2#
