### ISSUE TITLE
Potential incorrect path in #2.2 in documentation

### ISSUE THREAD

**Issue by prerak-jain** [PhonePe/pulse#7]
A potentially incorrect path mentioned in point 2.2: data/map/transaction/... (https://github.com/PhonePe/pulse/tree/master#22-datamaptransactionhovercountryindia20211json). Probably the correct path is: data/map/user/...

**Comment by nagarajue-179** [comment]
Thank you for bringing this to our notice. This has been fixed. 

https://github.com/PhonePe/pulse/pull/8
