### ISSUE TITLE
Understanding Hex Grid Level of Phone Pe Data

### ISSUE THREAD

**Issue by tishasehdev** [PhonePe/pulse#9]
Hi Team,

Thanks for uploading this really insightful data. I am a Geospatial Data Engineer and was trying to understand the granularity in terms of hex grids for this data. Could you please support/guide so as to how to map this data to grids. From my experience this looks like Uber's H3 gridding system.

**Comment by modi-herik-phonepe** [comment]
Thanks for reaching out.

We have created the data with [S2 Gridding system](https://s2geometry.io/) with the range of 7.5kms radius and the hexagon towers on the website are based on centroid of each cell and height represents number of transactions in that particular cell. The hexagon towers are just UI manifestation.

**Comment by haxzie** [comment]
Hey @modi-herik-phonepe, Where can I find this grid level data?
